=== GeoStudios/Centurion/test/jaxp/javax/xml/jaxp/unittest/validation/tck/Bug6963468.xsd
<!--
  ~ Copyright (c) 2023 Geo-Studios and/or its affiliates. All rights reserved.
  ~ DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
  ~
  ~ This code is free software; you can redistribute it and/or modify it under
  ~ the terms of the GNU General Public License version 2 only, as published
  ~ by the Free Software Foundation. Geo-Studios designates this particular
  ~ file as subject to the "Classpath" exception as provided
  ~ by Geo-Studio in the LICENSE file that accompanied this code.
  ~
  ~ This code is distributed in the hope that it will be useful, but WITHOUT
  ~ ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  ~ GNU General Public License version 2 for more details (a copy is
  ~ included in the LICENSE file that accompanied this code).
  ~
  ~ You should have received a copy of the GNU General Public License
  ~ version 2 along with this work; if not, write to the Free Software
  ~ Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
  -->

<xsd:schema id="MyXSD" targetNamespace="http://xsdtesting" xmlns="http://xsdtesting" xmlns:xsd="http://www.w3.org/2001/XMLSchema" attributeFormDefault="qualified" elementFormDefault="qualified">


	    <xsd:element name="root">
	      <xsd:complexType>
		<xsd:choice maxOccurs="unbounded">
		    <xsd:element ref="E1" minOccurs="0" maxOccurs="20"/>
		    <xsd:element ref="E3" minOccurs="0" maxOccurs="20"/>
		</xsd:choice>
	      </xsd:complexType>
	    </xsd:element>

	    <xsd:simpleType name="myType9">
		  <xsd:list itemType="myType10"/>
	  </xsd:simpleType>

	  <xsd:simpleType name="myType10">
        	<xsd:union memberTypes="xsd:float xsd:integer">
          		<xsd:simpleType>
		            <xsd:restriction base='xsd:boolean'/>
		        </xsd:simpleType>
		        <xsd:simpleType>
		            <xsd:restriction base='xsd:string'>
		              <xsd:enumeration value='x'/>
		              <xsd:enumeration value='y'/>
		            </xsd:restriction>
		        </xsd:simpleType>
	        </xsd:union>
	 </xsd:simpleType>

	<xsd:simpleType name="DeriveUnion">
	  <xsd:restriction base="myType10">
	  </xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name="CT1">
	  <xsd:attribute name="att1" type="myType10"/>
	</xsd:complexType>

	<xsd:complexType name="CT2">
	  <xsd:complexContent>
	    <xsd:restriction base="CT1">
		<xsd:attribute name="att1" type="xsd:integer"/>
	    </xsd:restriction>
	  </xsd:complexContent>
	</xsd:complexType>

	<xsd:element name="E1" type="myType10"/>
	<xsd:element name="E2" substitutionGroup="E1" type="xsd:integer"/>
	<xsd:element name="E3" type="CT2"/>
</xsd:schema>

=== GeoStudios/Centurion/test/jaxp/javax/xml/jaxp/unittest/validation/tck/Bug6963468.xml
<!--
  ~ Copyright (c) 2023 Geo-Studios and/or its affiliates. All rights reserved.
  ~ DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
  ~
  ~ This code is free software; you can redistribute it and/or modify it under
  ~ the terms of the GNU General Public License version 2 only, as published
  ~ by the Free Software Foundation. Geo-Studios designates this particular
  ~ file as subject to the "Classpath" exception as provided
  ~ by Geo-Studio in the LICENSE file that accompanied this code.
  ~
  ~ This code is distributed in the hope that it will be useful, but WITHOUT
  ~ ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  ~ GNU General Public License version 2 for more details (a copy is
  ~ included in the LICENSE file that accompanied this code).
  ~
  ~ You should have received a copy of the GNU General Public License
  ~ version 2 along with this work; if not, write to the Free Software
  ~ Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
  -->

<x:root
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://xsdtesting Bug6963468.xsd"
	xmlns:x="http://xsdtesting">

	<x:E1>1</x:E1>
	<x:E1>true</x:E1>
	<x:E1>false</x:E1>
	<x:E1>x</x:E1>
	<x:E1>y</x:E1>
	<x:E2>1</x:E2>
	<x:E3 x:att1="123"/>
</x:root>
